{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-agent-docker.serviceAccountName" . }}
  labels:
{{ include "azure-agent-docker.labels" . | nindent 4 }}
{{- end -}}
